name: ServerTutorial
main: pw.hwk.tutorial.ServerTutorial
version: maven-version-number
description: Tutorial plugin
authors: [hawkfalcon, gomeow, Frostalf, Trojaner]
website: hwk.pw
softdepend: [Vault, Multiverse-Core]
commands:
    tutorial:
        description: tutorial
permissions:
    tutorial.*:
        children:
            tutorial.use: true
            tutorial.create: true
    tutorial.create:
        default: OP
    tutorial.use:
        default: true
    tutorial.config:
        default: OP
